### ISSUE TITLE
If your email contains an underscore "_", the script would not see the cookie. 

### ISSUE THREAD

**Issue by kaitung123** [ndbroadbent/icloud_photos_downloader#152] opened 2020-06-01 02:56 UTC
Is there a temp fix I could do on my side to get this working?

**Comment by boredazfcuk** [comment] 2020-06-01 13:24
Are you sure that's your problem? I ran it fine for months with an e-mail address which contains underscores.

I changed because I had an issue receiving Family Safety confirmation e-mails. Apple Support confirmed that the issue was due to the underscore in my e-mail address and that I should remove it... Sure enough, I changed the e-mail address associated with my Apple ID to one without an underscore and the notification e-mails came through.

**Comment by menkej** [comment] 2020-10-16 21:07
Is this really/still an issue? I don't have an underscore in my iCloud email, so I can't reproduce it right now. @kaitung123 do you have any updates/further information?

**Comment by AndreyNikiforov** [comment] 2020-10-17 18:42
My email has underscore. Just tried latest (c87045d6f3ffd63a0ee44ad1cb6df834eca28c2c) with local docker build (`docker buildx build . -t ddd`) and `--folder-structure {:%Y/%Y-%m-%d} --auto-delete --threads-num 1 --no-progress-bar --until-found 20` params besides setup/auth-related. Worked with new auth MFA scenario as well as existing cookie.

@boredazfcuk are you using multi factor auth (MFA) on your Apple account?

**Comment by boredazfcuk** [comment] 2020-10-17 21:20
I am, but my Apple ID doesn't have an underscore in it any more. I used from around 08/2018 to 11/2019 without issue.

I had an issue raised about my Docker container not working correctly if the Apple ID had an underscore character in it last month. Maybe OP got confused and reported that issue here? https://github.com/boredazfcuk/docker-icloudpd/issues/27

**Comment by menkej** [comment] 2020-10-18 07:45
>  I used from around 08/2018 to 11/2019 without issue.

Ok, so I assume this issue is in this project by accident. I'll close it now. If you're still having an issue @kaitung123 feel free to reopen with additional info, if possible. Thanks!

**Closed by menkej** 2020-10-18 07:45 UTC
