### ISSUE TITLE
download_photos.py tries to connect to non-existing host p48-photosws.icloud.com

### ISSUE THREAD

**Issue by hreese** [ndbroadbent/icloud_photos_downloader#23] opened 2017-06-15 13:02 UTC
Login and 2-factor auth succeeded:
```
$ ./download_photos.py ./dest/ --username foo@bar.com --password XXXXXXXX --size original
Signing in...
Updating photos...
Traceback (most recent call last):
  File "./download_photos.py", line 231, in <module>
    download()
  File "/home/hreese/src/icloud_photos_downloader/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/hreese/src/icloud_photos_downloader/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/hreese/src/icloud_photos_downloader/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hreese/src/icloud_photos_downloader/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 55, in download
    updatePhotos(icloud)
  File "./download_photos.py", line 155, in updatePhotos
    icloud.photos.update()
  File "/home/hreese/src/icloud_photos_downloader/venv/lib/python2.7/site-packages/pyicloud/base.py", line 306, in photos
    self.params
  File "/home/hreese/src/icloud_photos_downloader/venv/lib/python2.7/site-packages/pyicloud/services/photos.py", line 35, in __init__
    params=self.params
  File "/home/hreese/src/icloud_photos_downloader/venv/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
    return self.request('GET', url, **kwargs)
  File "/home/hreese/src/icloud_photos_downloader/venv/lib/python2.7/site-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/home/hreese/src/icloud_photos_downloader/venv/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hreese/src/icloud_photos_downloader/venv/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/home/hreese/src/icloud_photos_downloader/venv/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p48-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber=14E45&dsid=xxxxxxxxxxx&clientId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f47f80603d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

Is that a bug in pyicloud or download_photos.py?

**Comment by matus-krizan** [comment] 2017-06-15 18:30
I'm having the same problem, worked two days ago, stopped working yesterday evening.

**Comment by ndbroadbent** [comment] 2017-06-15 19:43
Hi everyone, I'm sorry about that. I don't have time to look into this right now, but you might find some more information over at https://github.com/picklepete/pyicloud

Looks like this is the same issue: https://github.com/picklepete/pyicloud/issues/136

**Comment by chadj** [comment] 2017-06-20 05:30
I've been working on picklepete/pyicloud#136 over in [chadj/pyicloud/ckdatabasews](/chadj/pyicloud/tree/ckdatabasews) and since it contains a few backwards compatibly issues I decided to update icloud_photos_downloader to be compatible with these changes.  You can try out that update over at [chadj/icloud_photos_downloader/ckdatabasews](/chadj/icloud_photos_downloader/tree/ckdatabasews).  You'll need to install [chadj/pyicloud/ckdatabasews](/chadj/pyicloud/tree/ckdatabasews) first ofcourse.

I also added a new command line option

```
  --until-found INTEGER RANGE     Download most recently added photos until we
                                  find x number of previously downloaded
                                  consecutive photos (default: download all photos)
``` 
Which will drastically speed up what I think is the common use for using this command line tool

**Comment by jamescarlos** [comment] 2017-06-20 07:44
Thank you @chadj, I tested your branches out and I'm back to downloading the original photos off icloud. 👍  I briefly checked exif data (dates) and it looks good.

Can you provide more info regarding the `--until-found` option? I'm not sure how I would use it. How does this differ from `--recent`?

**Comment by itadder** [comment] 2017-06-20 11:43
anyone got this to work in windows 10 cmd prompt (CON HOST)?

**Comment by chadj** [comment] 2017-06-20 14:30
@jamescarlos yeah.  `--until-found` can be used instead of `--recent`.  `--until-found=x` begins iterating over the most recently added photos and downloads every photo until it finds `x` number of files that already exist on the disk.

In other words, it downloads all new files until it finds `x` number of files it has already downloaded.

Does that make more sense?

**Comment by jamescarlos** [comment] 2017-06-20 16:29
Perfect, thanks for the explanation @chadj.

**Comment by itadder** [comment] 2017-06-20 23:26
Has anyone gotten this to work in Windows 10 version of python?

**Comment by chadj** [comment] 2017-06-21 00:00
Which version of Python on Windows 10 are you using @itadder ?

**Comment by itadder** [comment] 2017-06-21 09:41
Python 2.7.13

**Comment by chadj** [comment] 2017-06-21 13:58
@itadder I just tried that setup and it worked for me.  What error are you getting?

**Comment by itadder** [comment] 2017-06-21 20:54
File "c:\Python27\lib\site-packages\click\core.py", line 535, in invoke
return callback(*args, **kwargs)
File "download_photos.py", line 55, in download
updatePhotos(icloud)
File "download_photos.py", line 155, in updatePhotos
icloud.photos.update()
File "c:\Python27\lib\site-packages\pyicloud\base.py", line 306, in photos
self.params
File "c:\Python27\lib\site-packages\pyicloud\services\photos.py", line 37, in init
response = request.json()
File "c:\Python27\lib\site-packages\requests\models.py", line 878, in json
self.content.decode(encoding), **kwargs
File "c:\Python27\lib\json_init_.py", line 339, in loads
return _default_decoder.decode(s)
File "c:\Python27\lib\json\decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "c:\Python27\lib\json\decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded


This is what I get...

**Comment by chadj** [comment] 2017-06-21 21:36
Ah, I forgot to update the requirements.txt file in my branch.  Uninstall both icloud_photos_downloader and pyicloud then reinstall.  That should fix the problem.

**Comment by itadder** [comment] 2017-06-22 09:51
Thanks

**Comment by steliosmilidonis** [comment] 2017-06-24 20:09
Hii tried the branch by @chadj however getting the following, any ideas?

Signing in...
Updating photos...
Traceback (most recent call last):
  File "./download_photos.py", line 231, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 55, in download
    updatePhotos(icloud)
  File "./download_photos.py", line 155, in updatePhotos
    icloud.photos.update()
AttributeError: 'PhotosService' object has no attribute 'update'

**Comment by steliosmilidonis** [comment] 2017-06-25 11:55
my bad used master branch instead of ckdatabasews , confirmed it works

**Comment by chadj** [comment] 2017-06-25 12:04
Perfect!  Glad its sorted out.

**Comment by mcirri** [comment] 2017-06-28 00:06
Hi I tried the updated chadj/pyicloud/ckdatabasews and the icloud_photos_downloader but I get the following:
Signing in...
Traceback (most recent call last):
  File "./download_photos.py", line 258, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 58, in download
    icloud = authenticate(username, password)
  File "./download_photos.py", line 132, in authenticate
    icloud = pyicloud.PyiCloudService(username, password)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 169, in __init__
    self.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 192, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Forbidden',))

It seems like the password is simply wrong but I checked it several time with the www.icloud.com and it is the correct password.

Is there anything clearly wrong? I am using Python 2.7.12 on ubuntu linux. Options were "--username" & "--password" I have the two factor enabled. It used to work for me before this error with the password stored in the keyring.

**Comment by chadj** [comment] 2017-06-28 15:12
@mcirri I'm not sure what the issue could be there.  I'd try removing the keychain from the equation and see if that works.  This is likely a separate issue.

**Comment by mcirri** [comment] 2017-06-28 15:21
How do you do that? I tried with the command "iCloud --username xxxxxxx --delete-from-key ring" but I get a different error on the username. I cannot verify right now.

**Comment by chadj** [comment] 2017-06-28 15:46
If you provide a password on the command line it will skip keychain access.  It's also possible Apple changed how 2fa is implemented on these end points.  Which might be the root cause here.  I'm not using 2fa currently.

**Comment by brendan-pike** [comment] 2017-07-05 02:55
Using the ckdatabasews branch I'm getting "Name or service not known", can anyone help?

```
Signing in...
Looking up all photos...
Traceback (most recent call last):
  File "./download_photos.py", line 231, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 62, in download
    photos = icloud.photos.all
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 306, in photos
    self.params
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 35, in __init__
    params=self.params
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p16-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber=14E45&dsid=1745167082&clientId=08B8A16C-612D-11E7-BD30-5404A628CDD8 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe500399550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by chadj** [comment] 2017-07-05 04:20
@brendan-pike it looks like you're not using the ckdatabasews branch of pyicloud.  Try reinstalling just that dependency

**Comment by freiit** [comment] 2017-07-05 15:35
The complete installation guide for that fix:

    git clone https://github.com/chadj/icloud_photos_downloader.git

 Uninstall if you have already tried to run:
 
    sudo pip uninstall git+https://github.com/chadj/pyicloud.git@ckdatabasews#egg=pyicloud

then

    sudo pip install -r requirements.txt

Now it should work.

**Comment by f1rf1n** [comment] 2017-07-21 12:13
The 'complete installation guide' posted by @freiit above does not work for me unfortunately. Is there somehting I am missing. After following the steps there I am still getting:

> File "/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p50-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber= <CUT>&dsid= >CUT< &clientId= >CUT< (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd91fcf7510>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by chadj** [comment] 2017-07-21 15:28
Try this @f1rf1n 

```
sudo pip uninstall pyicloud
```

```
git clone https://github.com/chadj/icloud_photos_downloader.git
```

```
git checkout ckdatabasews
```

```
sudo pip install -r requirements.txt
```

Checking out the branch was missing from those steps

**Comment by f1rf1n** [comment] 2017-07-22 11:24
Switching to the right branch makes sense. And it is working for me now, thanks all

**Comment by ndbroadbent** [comment] 2017-07-25 17:56
Hey @chadj thanks for the fix, I'll merge these changes in! Is there anything to watch out for, or is it all good to go?

**Comment by chadj** [comment] 2017-07-27 18:11
It should be all good to go.  I'm working on getting the pyicloud changes merged upstream but there's no eta on that right now.

**Comment by hadiasghari** [comment] 2017-08-13 07:40
See: https://github.com/picklepete/pyicloud/issues/136

**Comment by hadiasghari** [comment] 2017-08-13 07:42
Hi @chadj, I am updating the script to run with your pyicloud branch. Given the ```.all``` now returns a generator, is there a way to get the count of photos directly, other than ```len(list(...))```?

**Comment by chadj** [comment] 2017-08-13 14:31
@hadiasghari Yeah, there is a way to get the length.  Calling len() on a PhotoAlbum returns the length without iterating over the entire album.  That's used here:

https://github.com/chadj/icloud_photos_downloader/blob/ckdatabasews/download_photos.py#L63

**Comment by ndbroadbent** [comment] 2017-09-25 09:45
Update - these changes have been merged, so everything should be working now.

**Closed by ndbroadbent** 2017-09-25 09:45 UTC
