### ISSUE TITLE
Failed to establish a new connection: [Errno -2] Name or service not known',))

### ISSUE THREAD

**Issue by General13K7** [ndbroadbent/icloud_photos_downloader#27] opened 2017-07-08 12:52 UTC
Signing in...
Updating photos...
Traceback (most recent call last):
  File "./download_photos.py", line 231, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 55, in download
    updatePhotos(icloud)
  File "./download_photos.py", line 155, in updatePhotos
    icloud.photos.update()
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 306, in photos
    self.params
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 35, in __init__
    params=self.params
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p34-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber=14E45&dsid=1372480800&clientId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff37510df50>: Failed to establish a new connection: [Errno -2] Name or service not known',))

help me please

**Comment by sameersharma25** [comment] 2017-07-08 20:34
I am having the same exact issue

**Comment by jmordkoff** [comment] 2017-07-09 04:20
me  three. Is pcsRequired: True  the problem? 

(Pdb) p self.webservices['photos']
{u'url': u'https://p53-photosws.icloud.com:443', u'status': u'active', u'pcsRequired': True, u'uploadUrl': u'https://p53-uploadphotosws.icloud.com:443'}

**Comment by jmordkoff** [comment] 2017-07-09 05:15
https://github.com/ndbroadbent/icloud_photos_downloader/issues/23 solved this for me

**Comment by f1rf1n** [comment] 2017-07-17 19:58
@jmordkoff Would you mind elaborating? #23 is not that clear to me.

**Comment by chadj** [comment] 2017-07-21 15:31
This is definitely a duplicate of #23 which is ultimately due to picklepete/pyicloud#136 .

**Comment by hadiasghari** [comment] 2017-08-13 07:39
Hi @chadj, I am updating the script to run with your pyicloud branch. Since the .all now returns a generator, is there a way to get the count of photos directly, other than len(list(...)) ?

**Comment by ndbroadbent** [comment] 2017-09-25 09:47
Hello, sorry this is happening! This project is just a small wrapper around the [pyicloud](https://github.com/picklepete/pyicloud) library, so it might be better to post an issue over there.

**Closed by ndbroadbent** 2017-09-25 09:47 UTC

**Comment by Reese-Chen** [comment] 2022-10-17 15:18
So,what is the solution to this problem? I am facing the same problem.
